"""
worker_prompt_template.py — Renders worker task prompts from a Baton.
Domain-agnostic. Python 3.9 compatible. No external deps.

Rules embedded in every prompt:
- DB-write-immediately discipline (Vera's #1 rule)
- Tool call truncation (Vera's §7.1)
- Token budget awareness (two-layer enforcement)
- Handoff procedure
"""

from __future__ import annotations

import json
from typing import Any, Dict, Optional

# Soft/hard limits must match orchestrator constants
SOFT_BUDGET_DEFAULT = 60_000
HARD_BUDGET_DEFAULT = 75_000


def render_worker_prompt(
    domain: str,
    baton_json: str,
    sprint_num: int,
    time_remaining_seconds: int,
    token_budget: int = 80_000,
    soft_budget: Optional[int] = None,
    hard_budget: Optional[int] = None,
    db_path: str = "~/.openclaw/workspace/projects/loop-relay/swarm.db",
    job_id: str = "",
    worker_prompt_version: str = "v1",
    extra_instructions: str = "",
) -> str:
    """
    Render a complete worker task prompt from a baton.

    Parameters
    ----------
    domain : str
        Domain hint for the worker (e.g. "research", "yapcad", "security").
    baton_json : str
        JSON string of the v2 Baton.
    sprint_num : int
        This worker's sprint number (1-indexed).
    time_remaining_seconds : int
        Seconds left in the overall job time budget.
    token_budget : int
        Total token budget for this worker session.
    soft_budget : int
        Tokens at which worker must wrap up (default: 75% of token_budget).
    hard_budget : int
        Tokens at which orchestrator will force-kill (default: 94% of token_budget).
    db_path : str
        Path to swarm.db. Worker must write findings here before anything else.
    job_id : str
        The job/loop UUID. Worker uses this for all DB writes.
    worker_prompt_version : str
        Prompt version tag, for auditing.
    extra_instructions : str
        Domain-specific additions appended at the end.
    """
    soft = soft_budget if soft_budget is not None else int(token_budget * 0.75)
    hard = hard_budget if hard_budget is not None else int(token_budget * 0.94)

    time_remaining_str = _format_time(time_remaining_seconds)

    # Parse baton for display
    try:
        baton = json.loads(baton_json)
    except json.JSONDecodeError:
        baton = {}

    sprint_focus = baton.get("next_sprint_focus", "Continue research.")
    cost_so_far = baton.get("cost_so_far_usd", 0.0)
    open_questions_count = len(baton.get("open_questions", []))
    theses_count = len(baton.get("theses", []))
    loop_health = baton.get("loop_health", {})
    no_progress = loop_health.get("consecutive_no_progress_sprints", 0)

    # Convergence warning
    convergence_warning = ""
    if no_progress >= 2:
        convergence_warning = (
            f"\n⚠️  CONVERGENCE WARNING: {no_progress} consecutive sprints with zero novel findings. "
            "If this sprint also yields nothing new, prepare a CONCLUSION sprint summary instead of "
            "continuing research. The loop is converging."
        )

    # Digest context
    digest_section = ""
    digest = baton.get("digest")
    if digest:
        q_score = digest.get("quality_score", 0.0)
        digest_section = f"""
## Prior Research Digest (Sprints 1-{digest.get('generated_sprint', '?')})
Quality score: {q_score:.2f} (generated by {digest.get('model', 'unknown')})

{digest.get('text', '')}

> All raw findings are in the SQLite database. The digest is a compressed summary only.
> For specific claims, query: `findings WHERE job_id='{job_id}'`
"""
    else:
        digest_section = "\n## Prior Research\nNo digest yet. This is an early sprint.\n"

    # Anchor findings
    anchor_section = ""
    anchors = baton.get("anchor_findings", [])
    if anchors:
        anchor_lines = "\n".join(
            f"- [{a.get('id', '?')}] {a.get('content', '')[:300]}"
            for a in anchors[:10]
        )
        anchor_section = f"""
## Anchor Findings (Never Compress — Always True)
These findings have been marked ANCHOR. They are always carried verbatim:

{anchor_lines}
"""

    # Theses
    theses_section = ""
    theses = baton.get("theses", [])
    if theses:
        t_lines = "\n".join(
            f"- [{t.get('id')}] {t.get('status', 'open').upper()} "
            f"(confidence={t.get('confidence', 0):.2f}): {t.get('key_finding', '')[:200]}"
            for t in theses
        )
        theses_section = f"""
## Current Thesis State ({theses_count} theses)
{t_lines}
"""

    # Open questions
    questions_section = ""
    questions = baton.get("open_questions", [])
    if questions:
        q_lines = "\n".join(
            f"- [{q.get('id')}] [{q.get('priority', 'medium').upper()}] {q.get('text', '')}"
            + (f"\n  Suggested sources: {', '.join(q.get('suggested_sources', []))}"
               if q.get("suggested_sources") else "")
            for q in questions[:15]
        )
        questions_section = f"""
## Open Questions ({open_questions_count} open)
{q_lines}
"""

    prompt = f"""# Loop Relay Worker — Sprint {sprint_num}
Domain: {domain}
Job ID: {job_id}
Prompt version: {worker_prompt_version}
Sprint: {sprint_num}
Time remaining in job: {time_remaining_str}
Cost so far: ${cost_so_far:.4f}
{convergence_warning}

---

## Your Mission: Sprint {sprint_num}
{sprint_focus}

---
{digest_section}
{anchor_section}
{theses_section}
{questions_section}

---

## Token Budget — READ THIS BEFORE STARTING

Total allocated: {token_budget:,} tokens
Soft stop: {soft:,} tokens — YOU must stop at this point
Hard stop: {hard:,} tokens — ORCHESTRATOR will force-kill you

### What to do when you approach limits:
- At {soft:,} tokens consumed: STOP starting new sources or tool calls. Write sprint summary to DB immediately. Set handoff_type="budget_exhausted". Signal done.
- At {hard:,} tokens: The orchestrator will kill this session without warning. Make sure everything is in the DB.

**You cannot count tokens yourself. Estimate: every 4 characters ≈ 1 token.**
Monitor your output length. If you've written 240,000 characters since session start, you're near the soft limit.

---

## DB-Write-Immediately Discipline (NON-NEGOTIABLE)

**After EVERY tool call that returns results:**
1. IMMEDIATELY write findings to SQLite BEFORE processing them further
2. Use the findings table: `INSERT INTO findings (job_id, sprint_num, content, source, thesis_id, question_id, confidence) VALUES (...)`
3. DB path: `{db_path}`
4. Job ID for all writes: `{job_id}`

**Why:** If this session is killed mid-sprint, anything not in the DB is lost forever. The baton carries pointers to DB records — not the data itself.

**The rule:** Write first. Think second. Never buffer findings in context.

---

## Tool Call Truncation Rules

When a tool returns more than 2,000 tokens of content:
1. Extract only the relevant claim(s) — one or two sentences
2. Write: claim + source URL/ref to SQLite findings table IMMEDIATELY
3. Discard the raw content — do NOT quote it inline
4. Continue with: "Wrote finding [source] to DB."

Never paste large tool outputs into your reasoning. Your context window is finite and shared with the baton.

---

## Finding Quality Standards

For each finding:
- **content**: One to three sentences. Specific claim. No vague "X is important."
- **source**: Full URL or document reference
- **confidence**: 0.0-1.0 based on source quality and corroboration
- **thesis_id**: Link to a thesis if this confirms/refutes one (use T1, T2, etc.)
- **question_id**: Link to a question if this answers/informs one (use Q1, Q2, etc.)
- **is_anchor**: Set to 1 ONLY for findings you'd stake the whole loop on

---

## Handoff Procedure

When you are done (reached soft limit, answered the focus question, or time is up):

1. Write all pending findings to DB
2. Update theses table for any thesis whose status changed this sprint
3. Update questions table for any question resolved or newly raised this sprint
4. Write a sprint summary as an event:
   ```sql
   INSERT INTO events (job_id, sprint_num, event_type, payload_json)
   VALUES ('{job_id}', {sprint_num}, 'sprint_summary',
     '{{"summary": "...", "novel_findings": N, "handoff_type": "clean"}}');
   ```
5. Signal completion. The orchestrator will read the DB and generate the next baton.

---

## Full Baton JSON (for reference)

```json
{baton_json}
```

---
{extra_instructions}

Begin Sprint {sprint_num}. Write to DB before you think. Go.
"""
    return prompt.strip()


def render_conclusion_prompt(
    domain: str,
    baton_json: str,
    sprint_num: int,
    job_id: str,
    db_path: str = "~/.openclaw/workspace/projects/loop-relay/swarm.db",
) -> str:
    """
    Render a conclusion/synthesis sprint prompt.
    Used when loop_health.consecutive_no_progress_sprints >= CONVERGENCE_THRESHOLD.
    """
    try:
        baton = json.loads(baton_json)
    except json.JSONDecodeError:
        baton = {}

    cost_so_far = baton.get("cost_so_far_usd", 0.0)
    theses = baton.get("theses", [])

    theses_text = "\n".join(
        f"- [{t.get('id')}] {t.get('status', 'open').upper()} "
        f"(confidence={t.get('confidence', 0):.2f}): {t.get('key_finding', '')[:300]}"
        for t in theses
    ) or "(no theses)"

    prompt = f"""# Loop Relay — CONCLUSION SPRINT {sprint_num}
Domain: {domain}
Job ID: {job_id}
Total cost so far: ${cost_so_far:.4f}

The loop has converged. No novel findings in the last 3+ sprints.
Your task: write the final synthesis.

---

## Thesis Summary
{theses_text}

---

## Your Deliverable

Write a final research report to:
`{db_path}` → events table, event_type='final_report'

The report must include:
1. **Confirmed findings** — what do we know with high confidence?
2. **Refuted hypotheses** — what did the evidence disprove?
3. **Open questions** — what remains genuinely unresolved?
4. **Confidence calibration** — overall quality of evidence
5. **Recommended next steps** — if this research continues, where to focus?

Then write to events:
```sql
INSERT INTO events (job_id, sprint_num, event_type, payload_json)
VALUES ('{job_id}', {sprint_num}, 'final_report', '{{"report": "...full text..."}}');
```

Also update the job status:
```sql
UPDATE jobs SET status = 'converged' WHERE id = '{job_id}';
```

Full baton:
```json
{baton_json}
```

Write the final report. Be specific. Don't summarize vaguely.
"""
    return prompt.strip()


def _format_time(seconds: int) -> str:
    """Format seconds into human-readable string."""
    if seconds < 60:
        return f"{seconds}s"
    elif seconds < 3600:
        return f"{seconds // 60}m {seconds % 60}s"
    else:
        h = seconds // 3600
        m = (seconds % 3600) // 60
        return f"{h}h {m}m"


# ─── Domain-specific extra instructions ────────────────────────────────────────

DOMAIN_EXTRAS: Dict[str, str] = {
    "research": """
## Research-Specific Instructions
- Prefer primary sources: papers, official docs, data — not blog posts
- For each claim, note: author, publication, year, DOI/URL
- If two sources contradict, note both and flag as conflicting evidence
- Use web_search for discovery, web_fetch for full content
- Max 3 tool calls per source before moving on
""",

    "yapcad": """
## yapCAD Simulation Instructions
- Write geometry results (coordinates, measurements) to findings table immediately
- Source field should be: "yapcad:script_name.py:line_N"
- Confidence = 1.0 for deterministic geometry, lower for heuristic fits
- Save generated STL/DXF paths to findings as anchor findings
- Any render that succeeds: write the file path + parameters to DB immediately
""",

    "security": """
## Security Research Instructions
- Do NOT write credentials, keys, or hashes in findings.content — use placeholders
- Mark vulnerability findings as anchor findings (is_anchor=1)
- CVE IDs go in source field
- Severity in confidence field: critical=1.0, high=0.8, medium=0.5, low=0.2
- Cross-reference NIST NVD for all CVEs before marking confidence > 0.7
""",

    "market": """
## Market Research Instructions
- ALL price/value data must include timestamp in source field
- Never extrapolate prices — only report observed values
- Conflicting price data: write both findings with their respective sources
- Tickers in thesis_id field (e.g., thesis_id='AAPL')
- Confidence = data source reliability (exchange data=0.95, news=0.5, social=0.2)
""",
}


def get_domain_extras(domain: str) -> str:
    """Return domain-specific extra instructions, or empty string."""
    return DOMAIN_EXTRAS.get(domain.lower(), "")
